export { default as Home } from './home/Home'
export { default as About } from './about/About'
export { default as Contact } from './contact/Contact'
export { default as ErrorPage } from './errorPage/ErrorPage'
export { default as ProjectPage } from './project/ProjectPage'
